language: java
services:
  - docker

before_script:
   - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=True -B -V

script:
   - ./mvnw clean validate package
   - docker-compose up -d
   - DATABASE_HOST="0.0.0.0" java -jar target/UMUC495-Case-Management-1.0.jar
     
