language: java

services:
  - docker

before_install:
   - chmod +x ./mvnw

before_script:
   - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=True -B -V

script:
   - ./mvnw clean validate package
