version: '2.1'

services:
  db:
    image: postgres:11.7 
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "SuperSecret"
      POSTGRES_DB: case
      POSTGRES_USER: CMSC495
    networks:
      db:
        aliases:
          - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U CMSC495 -d case"]
      interval: 5s
      timeout: 30s
      retries: 3
networks:
  db:
    internal: false
